version: '3'
services:
  blog_deepak:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: blog_deepak
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next